// Blog yazıları — her biri tek bir yerel anahtar kelimeyi hedefler (SEO)
export const POSTS = [
  {
    slug: 'adana-protez-tirnak',
    kw: 'Adana protez tırnak',
    title: 'Adana Protez Tırnak: Fiyat, Modeller ve Bilinmesi Gerekenler',
    description: "Adana protez tırnak yaptırmadan önce bilmeniz gerekenler: uygulama, modeller, fiyatı belirleyen faktörler ve bakım. Yüreğir Mithra Nails Bar rehberi.",
    date: '2026-07-12',
    cover: '/gallery/g12.jpg',
    keywords: ['Adana protez tırnak', 'Adana protez tırnak fiyatları', 'protez tırnak modelleri', 'Yüreğir protez tırnak', 'jel protez tırnak', 'protez tırnak Adana'],
    body: [
      { p: "Adana protez tırnak yaptırmak isteyenler için doğru salonu seçmek kadar, sürecin nasıl işlediğini bilmek de önemlidir. Mithra Nails Bar olarak Yüreğir’de Adana protez tırnak uygulamalarını steril ekipman ve premium ürünlerle gerçekleştiriyor, her misafirimize kişiye özel form ve tasarım sunuyoruz." },
      { h: 'Adana protez tırnak nasıl uygulanır?' },
      { p: "Adana protez tırnak uygulaması, doğal tırnağın nazikçe hazırlanmasıyla başlar. Ardından tercih ettiğiniz forma (badem, kare, coffin, oval) göre jel veya polygel ile uzunluk verilir, kürlenir ve şekillendirilir. Amacımız doğal tırnağı yıpratmadan, hafif ama dayanıklı bir sonuç elde etmektir." },
      { h: 'Adana protez tırnak fiyatını ne belirler?' },
      { ul: ['Uygulanan sistem: jel, akrilik veya polygel', 'Tırnak formu ve uzunluğu', 'Nail art, taş ve 3D detay', 'Dolgu ve bakım standardı'] },
      { p: "Adana protez tırnak fiyatı sabit değildir; tasarımın detayına, forma ve salonun hijyen–ürün kalitesine göre değişir. Net fiyat için tırnak yapınızı görmemiz en doğrusudur." },
      { h: 'Adana protez tırnak bakımı' },
      { p: "Adana protez tırnak setinizin ömrü bakıma bağlıdır. Formu ve parlaklığı korumak için 3–4 haftada bir dolgu öneririz; çıkarma işlemi ise mutlaka uzman elinde yapılmalıdır. Doğru bakımla protez tırnak, doğal tırnağınıza zarar vermez." },
      { note: "Adana protez tırnak için randevu ve güncel fiyat: Instagram @mithranailsbar veya WhatsApp." },
    ],
  },
  {
    slug: 'adana-en-iyi-protez-tirnak',
    kw: 'Adana en iyi protez tırnak',
    title: 'Adana En İyi Protez Tırnak Nasıl Seçilir?',
    description: "Adana en iyi protez tırnak salonunu seçerken nelere dikkat etmeli? Hijyen, ürün kalitesi, deneyim ve kişiye özel tasarım. Yüreğir Mithra Nails Bar.",
    date: '2026-07-11',
    cover: '/gallery/g05.jpg',
    keywords: ['Adana en iyi protez tırnak', 'Adana protez tırnak', 'en iyi tırnakçı Adana', 'Yüreğir protez tırnak', 'protez tırnak salonu', 'Adana nail bar'],
    body: [
      { p: "Adana en iyi protez tırnak arayışındaysanız, kararınızı sadece fiyata göre vermemenizi öneririz. Adana en iyi protez tırnak deneyimi; hijyen, ürün kalitesi, uygulayıcı becerisi ve size özel yaklaşımın toplamıdır." },
      { h: 'Hijyen her şeyin önünde' },
      { p: "Adana en iyi protez tırnak salonunun ilk şartı sterilizasyondur. Mithra Nails Bar’da tüm ekipman her misafirden sonra steril edilir; törpü ve tamponlar kişiye özeldir. Sağlığınız, estetikten önce gelir." },
      { h: 'Ürün ve uygulama kalitesi' },
      { p: "Adana en iyi protez tırnak sonucunu premium jel ve polygel ürünler ile deneyimli uygulama belirler. Doğru aşındırma, doğru form ve doğru kürleme, hem dayanıklılığı hem doğal görünümü sağlar." },
      { h: 'Kişiye özel tasarım' },
      { ul: ['Cilt tonunuza uygun renk', 'El yapınıza uygun form', 'Yaşam temponuza uygun uzunluk', 'İsteğe göre nail art ve taş'] },
      { p: "Bizce Adana en iyi protez tırnak, katalogdan seçtirilen değil; sizi dinleyerek birlikte kurgulanan tasarımdır. Bu yüzden her seans danışmayla başlar." },
      { note: "Adana en iyi protez tırnak deneyimi için randevu: @mithranailsbar." },
    ],
  },
  {
    slug: 'adana-yuregir-protez-tirnak',
    kw: 'Adana Yüreğir protez tırnak',
    title: 'Adana Yüreğir Protez Tırnak — Size En Yakın Nail Bar',
    description: "Adana Yüreğir protez tırnak için doğru adres. Yüreğir ve çevresine yakın konum, steril ekipman, kişiye özel tasarım. Mithra Nails Bar.",
    date: '2026-07-09',
    cover: '/gallery/g14.jpg',
    keywords: ['Adana Yüreğir protez tırnak', 'Yüreğir protez tırnak', 'Adana protez tırnak', 'Yüreğir tırnakçı', 'Yüreğir nail bar', 'en yakın tırnakçı'],
    body: [
      { p: "Adana Yüreğir protez tırnak yaptırmak istiyorsanız, size en yakın nail bar’ı tercih etmek hem zaman hem konfor kazandırır. Mithra Nails Bar, Adana Yüreğir protez tırnak uygulamalarında bölgeye yakın konumu ve kişiye özel yaklaşımıyla öne çıkar." },
      { h: 'Neden yakın konum önemli?' },
      { p: "Adana Yüreğir protez tırnak uygulaması ortalama 90–120 dakika sürer. Yakın bir salon seçmek, hem randevuya rahat gelmenizi hem de dolgu ve bakım için pratik bir düzen kurmanızı sağlar." },
      { h: 'Yüreğir ve çevresi' },
      { p: "Adana Yüreğir protez tırnak için Yüreğir, Seyhan, Sarıçam ve çevresinden misafirlerimizi ağırlıyoruz. Ulaşımı kolay konumumuzla, size en yakın nail bar olmayı hedefliyoruz." },
      { h: 'Nasıl randevu alınır?' },
      { ul: ['Instagram @mithranailsbar üzerinden DM', 'WhatsApp ile hızlı mesaj', 'İstediğiniz uygulama ve saat bilgisi', 'Varsa referans fotoğrafı'] },
      { p: "Adana Yüreğir protez tırnak randevunuzu birkaç mesajla oluşturuyoruz; kararsızsanız size en uygun formu birlikte belirliyoruz." },
      { note: "Adana Yüreğir protez tırnak için hemen yazın: @mithranailsbar." },
    ],
  },
  {
    slug: 'yuregir-protez-tirnak',
    kw: 'Yüreğir protez tırnak',
    title: 'Yüreğir Protez Tırnak: Doğal ve Kalıcı Sonuç',
    description: "Yüreğir protez tırnak uygulamaları: badem, kare ve coffin formlar, doğal görünüm ve uzun ömür. Yüreğir Mithra Nails Bar ile tanışın.",
    date: '2026-07-07',
    cover: '/gallery/g01.jpg',
    keywords: ['Yüreğir protez tırnak', 'Yüreğir tırnakçı', 'Adana Yüreğir protez tırnak', 'Yüreğir nail art', 'protez tırnak formları', 'Yüreğir kalıcı oje'],
    body: [
      { p: "Yüreğir protez tırnak yaptırmak, doğal görünümlü ve kalıcı bir sonuç isteyenlerin ilk tercihidir. Mithra Nails Bar’da Yüreğir protez tırnak uygulamalarını, tırnak sağlığını önceleyen bir yaklaşımla gerçekleştiriyoruz." },
      { h: 'Form seçenekleri' },
      { p: "Yüreğir protez tırnak uygularken badem, kare, coffin ve oval gibi formlar arasından size en çok yakışanı birlikte seçeriz. Doğru form, hem estetik hem günlük kullanım konforu demektir." },
      { h: 'Doğal görünüm' },
      { p: "İyi bir Yüreğir protez tırnak, uzaktan protez olduğu anlaşılmayacak kadar doğal olmalıdır. Esnek jel yapısı, ince modelleme ve aynadan parlaklık ile bu sonucu hedefliyoruz." },
      { h: 'Kalıcılık ve bakım' },
      { ul: ['3–4 haftada bir dolgu', 'Eldivenle ev işi', 'Kütiküle besleyici yağ', 'Uzman elinde çıkarma'] },
      { p: "Yüreğir protez tırnak setiniz doğru bakımla haftalarca ilk günkü gibi kalır. Yüreğir protez tırnak dolgusu için zamanı geldiğinde size hatırlatma da yapıyoruz." },
      { note: "Yüreğir protez tırnak randevusu için: @mithranailsbar." },
    ],
  },
  {
    slug: 'adana-kalici-oje',
    kw: 'Adana kalıcı oje',
    title: 'Adana Kalıcı Oje: Haftalarca Parlaklık',
    description: "Adana kalıcı oje uygulaması nedir, ne kadar dayanır, 300+ renk seçeneği. Yüreğir Mithra Nails Bar ile haftalarca kalıcı parlaklık.",
    date: '2026-07-06',
    cover: '/gallery/g03.jpg',
    keywords: ['Adana kalıcı oje', 'Adana kalıcı oje fiyatları', 'kalıcı oje', 'Yüreğir kalıcı oje', 'Adana jel tırnak', 'kalıcı oje renkleri'],
    body: [
      { p: "Adana kalıcı oje, doğal tırnağınıza haftalarca süren renk ve parlaklık kazandıran pratik bir çözümdür. Mithra Nails Bar’da Adana kalıcı oje uygulamasını 300’ü aşkın renk seçeneğiyle sunuyoruz." },
      { h: 'Adana kalıcı oje ne kadar dayanır?' },
      { p: "Adana kalıcı oje ortalama 2–3 hafta dayanır. Süre; tırnak uzama hızınıza ve günlük alışkanlıklarınıza göre değişir. İlk 24 saat suyla uzun temastan kaçınmanız kalıcılığı artırır." },
      { h: 'Kimler için ideal?' },
      { p: "Tırnakları sağlıklı ve yeterli uzunlukta olup sadece uzun ömürlü renk isteyenler için Adana kalıcı oje birebirdir. Uzatma gerekmeden bakımlı ve şık eller elde edersiniz." },
      { h: 'Renk ve tasarım' },
      { ul: ['Nude ve süt tonları', 'Canlı ve mevsimlik renkler', 'French ve babyboomer', 'İnce nail art detayları'] },
      { p: "Adana kalıcı oje ile sade bir günlük görünümden özel gün tasarımına kadar geniş bir yelpaze mümkündür. Adana kalıcı oje çıkarma işlemini de tırnağa zarar vermeden yapıyoruz." },
      { note: "Adana kalıcı oje randevusu için: @mithranailsbar." },
    ],
  },
  {
    slug: 'adana-nail-art',
    kw: 'Adana nail art',
    title: 'Adana Nail Art: Kişiye Özel Tırnak Tasarımı',
    description: "Adana nail art ile tırnaklarınıza imza dokunuşu: french, ombre, taşlı ve minimal tasarımlar. Yüreğir Mithra Nails Bar.",
    date: '2026-07-04',
    cover: '/gallery/g06.jpg',
    keywords: ['Adana nail art', 'Adana tırnak tasarım', 'nail art', 'french tırnak', 'ombre tırnak', 'Yüreğir nail art'],
    body: [
      { p: "Adana nail art, tırnaklarınızı sizi anlatan küçük bir tuvale dönüştürür. Mithra Nails Bar’da Adana nail art uygulamalarını, elinize ve tarzınıza göre tamamen kişiye özel kurguluyoruz." },
      { h: 'Popüler Adana nail art tarzları' },
      { ul: ['Nude ve milky french', 'Babyboomer ve ombre', 'Taşlı minimal tasarımlar', 'Kromlu ve aynalı parlaklık'] },
      { p: "Adana nail art derken az ama öz detayları da, iddialı tam set tasarımları da uyguluyoruz. Yıldız, nazar ve çizgi gibi minimal dokunuşlar günlük kullanımda çok tercih ediliyor." },
      { h: 'Referansınızı getirin' },
      { p: "En güzel Adana nail art, size yakışandır. Pinterest ya da Instagram kaydınızı paylaşın; tasarımı el yapınıza ve cilt tonunuza göre birlikte yorumlayalım." },
      { h: 'Dayanıklılık' },
      { p: "Adana nail art tasarımları hem kalıcı oje hem protez tırnak üzerine uygulanabilir. Doğru bakımla desenler haftalarca canlı kalır." },
      { note: "Adana nail art için modelinizi @mithranailsbar DM’den paylaşın." },
    ],
  },
  {
    slug: 'adana-jel-tirnak',
    kw: 'Adana jel tırnak',
    title: 'Adana Jel Tırnak: Doğala En Yakın Sistem',
    description: "Adana jel tırnak nedir, protez ve akrilikten farkı nedir? Esnek yapı, doğal görünüm ve bakım. Yüreğir Mithra Nails Bar.",
    date: '2026-07-03',
    cover: '/gallery/g10.jpg',
    keywords: ['Adana jel tırnak', 'jel tırnak', 'Adana protez tırnak', 'jel güçlendirme', 'Adana jel tırnak fiyatları', 'Yüreğir jel tırnak'],
    body: [
      { p: "Adana jel tırnak, esnek yapısı ve doğal görünümüyle en çok tercih edilen sistemlerden biridir. Mithra Nails Bar’da Adana jel tırnak uygulamasını, tırnak sağlığını koruyarak yapıyoruz." },
      { h: 'Jel, akrilik ve polygel farkı' },
      { p: "Adana jel tırnak; akriliğe göre daha esnek ve doğaldır, polygele göre daha hafif bir his verir. Hangi sistemin size uygun olduğunu tırnak yapınıza bakarak öneriyoruz." },
      { h: 'Jel güçlendirme' },
      { p: "Tırnağınızı uzatmadan sağlamlaştırmak istiyorsanız, Adana jel tırnak yerine jel güçlendirme de ideal bir seçenektir. Kırılma ve yıpranmaya karşı koruyucu bir katman sağlar." },
      { h: 'Bakım' },
      { ul: ['3–4 haftada bir yenileme', 'İlk gün suyla uzun temastan kaçınma', 'Uzman elinde çıkarma', 'Kütikül bakımı'] },
      { p: "Adana jel tırnak setiniz doğru bakımla uzun süre parlak ve sağlam kalır. Adana jel tırnak fiyatını da tasarım detayına göre birlikte netleştiriyoruz." },
      { note: "Adana jel tırnak randevusu için: @mithranailsbar." },
    ],
  },
  {
    slug: 'yuregir-kalici-oje',
    kw: 'Yüreğir kalıcı oje',
    title: 'Yüreğir Kalıcı Oje: Bakımlı Eller İçin',
    description: "Yüreğir kalıcı oje uygulaması: uzun ömürlü renk, geniş palet ve nazik çıkarma. Size en yakın nail bar Mithra Nails Bar Yüreğir.",
    date: '2026-07-01',
    cover: '/gallery/g09.jpg',
    keywords: ['Yüreğir kalıcı oje', 'Adana kalıcı oje', 'kalıcı oje', 'Yüreğir tırnakçı', 'kalıcı oje fiyatları', 'Yüreğir nail bar'],
    body: [
      { p: "Yüreğir kalıcı oje, bakımlı ve şık eller isteyenler için pratik bir çözümdür. Mithra Nails Bar’da Yüreğir kalıcı oje uygulamasını geniş renk paletiyle ve nazik çıkarma yöntemiyle sunuyoruz." },
      { h: 'Neden kalıcı oje?' },
      { p: "Klasik ojeden farklı olarak Yüreğir kalıcı oje, UV/LED lambada kürlenir ve haftalarca dökülmeden kalır. Yoğun tempoda bile ellerinizin bakımlı görünmesini sağlar." },
      { h: 'Ne kadar dayanır?' },
      { p: "Yüreğir kalıcı oje ortalama 2–3 hafta dayanır. Tırnak uzama hızınıza göre değişse de, doğru bakımla bu süreyi rahatça yakalarsınız." },
      { h: 'Renk seçenekleri' },
      { ul: ['Nude ve pastel tonlar', 'Klasik kırmızı ve bordo', 'French ve babyboomer', 'İnce nail art'] },
      { p: "Yüreğir kalıcı oje ile hem sade günlük görünüm hem özel gün tasarımı mümkün. Yüreğir kalıcı oje çıkarma işlemini de tırnağınızı yıpratmadan yapıyoruz." },
      { note: "Yüreğir kalıcı oje için randevu: @mithranailsbar." },
    ],
  },
  {
    slug: 'adana-manikur-pedikur',
    kw: 'Adana manikür pedikür',
    title: 'Adana Manikür Pedikür: Baştan Ayağa Bakım',
    description: "Adana manikür pedikür ile ellerinize ve ayaklarınıza profesyonel bakım. Klasik ve SPA seçenekleri. Yüreğir Mithra Nails Bar.",
    date: '2026-06-29',
    cover: '/gallery/g08.jpg',
    keywords: ['Adana manikür pedikür', 'Adana manikür', 'Adana pedikür', 'el bakımı', 'ayak bakımı', 'Yüreğir manikür pedikür'],
    body: [
      { p: "Adana manikür pedikür, sadece estetik değil aynı zamanda bir bakım ritüelidir. Mithra Nails Bar’da Adana manikür pedikür hizmetini klasik ve SPA seçenekleriyle sunuyoruz." },
      { h: 'Manikür' },
      { p: "Adana manikür pedikür kapsamında el bakımı; törpüleme, kütikül düzenleme ve dilediğiniz renkte oje uygulamasını içerir. SPA manikürde peeling ve maske ile bakım zenginleştirilir." },
      { h: 'Pedikür' },
      { p: "Ayak bakımı, özellikle yaz aylarının vazgeçilmezidir. Adana manikür pedikür ile ayaklarınıza da bakımlı ve uzun ömürlü bir görünüm kazandırıyoruz." },
      { h: 'Hijyen' },
      { ul: ['Her misafirden sonra steril ekipman', 'Kişiye özel törpü ve tampon', 'Premium bakım ürünleri', 'Randevulu sistem'] },
      { p: "Adana manikür pedikür seansında acele etmiyoruz; siz kahvenizi yudumlarken gerisini biz hallediyoruz. Adana manikür pedikür randevunuzu kolayca oluşturabilirsiniz." },
      { note: "Adana manikür pedikür için randevu: @mithranailsbar." },
    ],
  },
  {
    slug: 'adana-gelin-tirnagi',
    kw: 'Adana gelin tırnağı',
    title: 'Adana Gelin Tırnağı: Düğün Günü İçin Kusursuz Eller',
    description: "Adana gelin tırnağı rehberi: model seçimi, prova zamanı ve bakım. Düğün gününüzde eller de kusursuz görünsün. Yüreğir Mithra Nails Bar.",
    date: '2026-06-27',
    cover: '/gallery/g11.jpg',
    keywords: ['Adana gelin tırnağı', 'gelin tırnağı', 'düğün tırnağı', 'Adana protez tırnak', 'özel gün tırnak', 'Yüreğir gelin tırnağı'],
    body: [
      { p: "Adana gelin tırnağı, düğün gününüzün en çok fotoğraflanan detaylarından biridir. Yüzük, buket ve söz anında ellerinizin de parlaması için Adana gelin tırnağı planlamasını erkenden yapmanızı öneririz." },
      { h: 'Ne zaman yaptırmalı?' },
      { p: "Adana gelin tırnağı için ideal zaman, düğünden 1–2 gün öncesidir; böylece hem taze kalır hem son rötuşlara vakit olur. Renk ve model provasını ise birkaç hafta önceden yapmak en güvenlisidir." },
      { h: 'Model seçimi' },
      { ul: ['Zamansız nude french veya babyboomer', 'Zarif ışıltı için taşlı minimal', 'Gelinliğe ve yüzüğe uyumlu ton', 'Uzun ömür için protez tırnak'] },
      { p: "Adana gelin tırnağı seçiminde abartıdan çok zarafeti önceriz; tasarımı gelinliğinize ve tarzınıza göre birlikte belirleriz." },
      { h: 'Bakım' },
      { p: "Adana gelin tırnağı öncesi el bakımı ve kütikül düzenlemesiyle eller kusursuz görünür. Özel gününüz için Adana gelin tırnağı randevunuzu erkenden ayırtmanızı öneririz." },
      { note: "Adana gelin tırnağı için erkenden yer ayırtın: @mithranailsbar." },
    ],
  },
];

export function getPost(slug) {
  return POSTS.find((p) => p.slug === slug);
}
